/**
 * Demo: build a from-scratch design system, persist it to DESIGN.md,
 * confirm it would flow into the agent prompt, and render a mock webapp
 * that consumes the exact tokens.
 *
 * Run with: pnpm tsx examples/from-scratch-system/build-demo.ts
 *
 * This is a non-interactive end-to-end proof of the design-system parity
 * work. No LLM call is made (would require an API key + cost real money).
 * Instead the script:
 *   1. Constructs a custom StoredDesignSystem (Aurora — purple/cyan,
 *      deliberately distinct from the warm-cream ATV default)
 *   2. Writes a DESIGN.md to examples/from-scratch-system/DESIGN.md
 *      via the same rewriteDesignMd() the IPC handler uses
 *   3. Calls formatDesignSystem() — the EXACT function packages/core uses
 *      to inject design tokens into the LLM prompt — and writes the prompt
 *      fragment to PROMPT_FRAGMENT.txt so we can confirm the custom values
 *      would reach the model
 *   4. Renders mockup.html using the same tokens, so a human can see the
 *      design system applied to a real UI
 *
 * Everything in this folder is a build artifact — feel free to delete and
 * re-run to regenerate.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { StoredDesignSystem } from '@atv-design/shared';
import { rewriteDesignMd } from '../../apps/desktop/src/main/design-md';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Step 1: Build "Aurora" — a from-scratch design system ────────────────────

const aurora: StoredDesignSystem = {
  schemaVersion: 1,
  rootPath: __dirname,
  displayName: 'Aurora',
  source: { kind: 'folder', value: __dirname },
  isBuiltIn: false,
  userEdited: true,
  extractedAt: new Date().toISOString(),
  sourceFiles: ['DESIGN.md', 'mockup.html'],
  summary:
    'Aurora: deep-violet surfaces with electric cyan accents, geometric sans for UI and a humanist serif for editorial moments. Built for late-night creative tools.',
  colors: [
    'oklch(0.18 0.06 290)', // surface-base: deep violet
    'oklch(0.24 0.08 285)', // surface-raised
    'oklch(0.32 0.1 280)', // surface-elevated
    'oklch(0.82 0.18 200)', // accent: electric cyan
    'oklch(0.72 0.22 195)', // accent-hover
    'oklch(0.95 0.02 200)', // text-primary
    'oklch(0.72 0.02 210)', // text-secondary
    'oklch(0.4 0.05 285)', // border
  ],
  fonts: ['"Cal Sans"', '"Inter Variable"', '"IBM Plex Serif"', '"JetBrains Mono"'],
  spacing: ['2px', '4px', '8px', '12px', '20px', '32px', '52px', '84px'],
  radius: ['4px', '8px', '12px', '20px', '9999px'],
  shadows: [
    '0 1px 2px oklch(0.05 0.04 290 / 0.4)',
    '0 4px 16px oklch(0.05 0.04 290 / 0.5), 0 1px 2px oklch(0.05 0.04 290 / 0.3)',
    '0 0 0 1px oklch(0.82 0.18 200 / 0.3), 0 0 24px oklch(0.82 0.18 200 / 0.2)',
  ],
  components: [
    {
      name: 'Buttons',
      rule: 'Primary buttons use --color-accent on --color-surface-base with --radius-md. Hover lifts to --color-accent-hover with a 2px glow shadow. Never use gradients — Aurora reads as flat with electric color accents only.',
    },
    {
      name: 'Cards',
      rule: 'Cards use --color-surface-raised with --radius-lg and the inset shadow. Avoid borders — surface elevation alone separates content. Padding follows --space-5.',
    },
    {
      name: 'Inputs',
      rule: 'Inputs are borderless on --color-surface-elevated with --radius-sm. Focus state pulls a 2px cyan ring via box-shadow, never outline. Height 40px minimum for touch parity.',
    },
    {
      name: 'Headings',
      rule: 'h1 and h2 use IBM Plex Serif with tight tracking (-0.02em). h3+ uses Cal Sans. Body uses Inter Variable. Never mix two display faces in the same view.',
    },
    {
      name: 'Empty states',
      rule: 'A serif tagline, one cyan accent button, and a thin geometric line drawing. Never use emoji or stock illustrations.',
    },
  ],
};

// ── Step 2: Write DESIGN.md via the SAME function the IPC handler uses ───────

const existingDesignMd = `# DESIGN.md

Design: Aurora demo

This file is generated by examples/from-scratch-system/build-demo.ts.

## 1. Product and audience

A late-night creative tool for visual artists working in dark studios.
Aurora trades the warm editorial feel of the ATV default for cold cinema palette.

## 2. Brand personality

- Confident, technical, after-hours
- Electric without being loud
- Serif moments inside otherwise geometric chrome
`;

const designMd = rewriteDesignMd(existingDesignMd, aurora);
const designMdPath = join(__dirname, 'DESIGN.md');
writeFileSync(designMdPath, designMd, 'utf8');

// ── Step 3: Capture what the agent prompt would receive ──────────────────────

/** Mirror of packages/core/src/agent.ts formatDesignSystem (kept local so this
 *  demo script doesn't import from the bundled-only core package). If the
 *  source ever diverges, update this script and document the drift in
 *  components.added-to-prompt section. */
function formatDesignSystemForPrompt(ds: StoredDesignSystem): string {
  const lines = [
    '## Design system to follow',
    `Root path: ${ds.rootPath}`,
    `Summary: ${ds.summary}`,
  ];
  if (ds.colors.length > 0) lines.push(`Colors: ${ds.colors.join(', ')}`);
  if (ds.fonts.length > 0) lines.push(`Fonts: ${ds.fonts.join(', ')}`);
  if (ds.spacing.length > 0) lines.push(`Spacing: ${ds.spacing.join(', ')}`);
  if (ds.radius.length > 0) lines.push(`Radius: ${ds.radius.join(', ')}`);
  if (ds.shadows.length > 0) lines.push(`Shadows: ${ds.shadows.join(', ')}`);
  if (ds.components && ds.components.length > 0) {
    lines.push('Component rules:');
    for (const c of ds.components) lines.push(`- ${c.name}: ${c.rule}`);
  }
  if (ds.sourceFiles.length > 0) {
    lines.push(`Source files: ${ds.sourceFiles.join(', ')}`);
  }
  return lines.join('\n');
}

const promptFragment = formatDesignSystemForPrompt(aurora);
writeFileSync(join(__dirname, 'PROMPT_FRAGMENT.txt'), promptFragment, 'utf8');

// ── Step 4: Render a mock webapp using the exact tokens ──────────────────────

const c = aurora.colors;
const f = aurora.fonts;
const s = aurora.spacing;
const r = aurora.radius;
const sh = aurora.shadows;

const mockHtml = `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Aurora — Late-night creative dashboard</title>
  <link rel="preconnect" href="https://rsms.me/" />
  <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
  <style>
    :root {
      --color-surface-base: ${c[0]};
      --color-surface-raised: ${c[1]};
      --color-surface-elevated: ${c[2]};
      --color-accent: ${c[3]};
      --color-accent-hover: ${c[4]};
      --color-text-primary: ${c[5]};
      --color-text-secondary: ${c[6]};
      --color-border: ${c[7]};

      --font-display: ${f[2]}, Georgia, serif;
      --font-sans: ${f[1]}, system-ui, sans-serif;
      --font-mono: ${f[3]}, ui-monospace, monospace;

      --space-1: ${s[0]};
      --space-2: ${s[1]};
      --space-3: ${s[2]};
      --space-4: ${s[3]};
      --space-5: ${s[4]};
      --space-6: ${s[5]};
      --space-7: ${s[6]};
      --space-8: ${s[7]};

      --radius-sm: ${r[0]};
      --radius-md: ${r[1]};
      --radius-lg: ${r[2]};
      --radius-xl: ${r[3]};
      --radius-full: ${r[4]};

      --shadow-soft: ${sh[0]};
      --shadow-elevated: ${sh[1]};
      --shadow-glow: ${sh[2]};
    }

    * { box-sizing: border-box; margin: 0; padding: 0; }
    html, body { height: 100%; }
    body {
      font-family: var(--font-sans);
      background: var(--color-surface-base);
      color: var(--color-text-primary);
      line-height: 1.5;
      -webkit-font-smoothing: antialiased;
    }

    /* Layout */
    .app { display: grid; grid-template-columns: 240px 1fr; min-height: 100vh; }
    .sidebar {
      background: var(--color-surface-raised);
      padding: var(--space-5);
      border-right: 1px solid var(--color-border);
      display: flex; flex-direction: column; gap: var(--space-5);
    }
    .main {
      padding: var(--space-6);
      display: flex; flex-direction: column; gap: var(--space-6);
      overflow-y: auto;
    }

    /* Logo */
    .logo {
      font-family: var(--font-display);
      font-size: 28px;
      font-weight: 600;
      letter-spacing: -0.02em;
    }
    .logo .glyph { color: var(--color-accent); }

    /* Nav */
    .nav { display: flex; flex-direction: column; gap: var(--space-1); }
    .nav-item {
      padding: var(--space-3) var(--space-4);
      border-radius: var(--radius-md);
      color: var(--color-text-secondary);
      text-decoration: none;
      font-size: 14px;
      font-weight: 500;
      transition: all 150ms ease;
    }
    .nav-item:hover { background: var(--color-surface-elevated); color: var(--color-text-primary); }
    .nav-item.active {
      background: var(--color-surface-elevated);
      color: var(--color-accent);
      box-shadow: var(--shadow-glow);
    }

    /* Header */
    .header { display: flex; justify-content: space-between; align-items: flex-end; gap: var(--space-5); }
    .title {
      font-family: var(--font-display);
      font-size: 44px;
      line-height: 1.1;
      letter-spacing: -0.02em;
      font-weight: 500;
    }
    .subtitle { color: var(--color-text-secondary); font-size: 15px; margin-top: var(--space-3); }

    /* Button — follows Components.Buttons rule from the design system */
    .btn {
      display: inline-flex;
      align-items: center;
      gap: var(--space-2);
      padding: var(--space-3) var(--space-5);
      border: 0;
      border-radius: var(--radius-md);
      background: var(--color-accent);
      color: var(--color-surface-base);
      font-family: inherit;
      font-size: 14px;
      font-weight: 600;
      letter-spacing: -0.005em;
      cursor: pointer;
      transition: all 180ms ease;
    }
    .btn:hover {
      background: var(--color-accent-hover);
      box-shadow: var(--shadow-glow);
    }
    .btn.btn-ghost {
      background: transparent;
      color: var(--color-text-secondary);
      border: 1px solid var(--color-border);
    }
    .btn.btn-ghost:hover {
      color: var(--color-text-primary);
      background: var(--color-surface-raised);
    }

    /* Card — follows Components.Cards rule */
    .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: var(--space-5); }
    .card {
      background: var(--color-surface-raised);
      border-radius: var(--radius-lg);
      padding: var(--space-5);
      box-shadow: var(--shadow-soft);
      display: flex; flex-direction: column; gap: var(--space-3);
    }
    .card .label {
      font-size: 11px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      color: var(--color-accent);
    }
    .card .value {
      font-family: var(--font-mono);
      font-size: 32px;
      font-feature-settings: 'tnum';
      letter-spacing: -0.02em;
    }
    .card .trend { font-size: 13px; color: var(--color-text-secondary); }

    /* Input — follows Components.Inputs rule */
    .input-row { display: flex; gap: var(--space-3); }
    .input {
      flex: 1;
      height: 40px;
      padding: 0 var(--space-4);
      border: 0;
      border-radius: var(--radius-sm);
      background: var(--color-surface-elevated);
      color: var(--color-text-primary);
      font-family: inherit;
      font-size: 14px;
    }
    .input:focus { outline: none; box-shadow: 0 0 0 2px var(--color-accent); }

    /* Activity panel */
    .panel {
      background: var(--color-surface-raised);
      border-radius: var(--radius-lg);
      padding: var(--space-5);
      box-shadow: var(--shadow-elevated);
    }
    .panel h2 {
      font-family: var(--font-display);
      font-size: 22px;
      letter-spacing: -0.01em;
      margin-bottom: var(--space-4);
    }
    .row {
      display: grid;
      grid-template-columns: 1fr auto auto;
      gap: var(--space-4);
      align-items: center;
      padding: var(--space-3) 0;
      border-bottom: 1px solid var(--color-border);
      font-size: 14px;
    }
    .row:last-child { border-bottom: 0; }
    .row .who { color: var(--color-text-primary); }
    .row .what { color: var(--color-text-secondary); font-family: var(--font-mono); font-size: 12px; }
    .row .when { color: var(--color-text-secondary); font-size: 12px; }

    /* Badge */
    .badge {
      display: inline-flex;
      align-items: center;
      gap: var(--space-1);
      padding: 2px var(--space-3);
      border-radius: var(--radius-full);
      background: var(--color-surface-elevated);
      color: var(--color-accent);
      font-size: 11px;
      font-weight: 600;
      letter-spacing: 0.04em;
    }
    .badge::before {
      content: '';
      width: 6px; height: 6px;
      border-radius: 50%;
      background: var(--color-accent);
      box-shadow: 0 0 8px var(--color-accent);
    }
  </style>
</head>
<body>
  <div class="app">
    <aside class="sidebar">
      <div class="logo">Aurora<span class="glyph">.</span></div>
      <nav class="nav">
        <a class="nav-item active" href="#">Overview</a>
        <a class="nav-item" href="#">Sessions</a>
        <a class="nav-item" href="#">Artifacts</a>
        <a class="nav-item" href="#">Models</a>
        <a class="nav-item" href="#">Settings</a>
      </nav>
      <div style="margin-top: auto; font-size: 12px; color: var(--color-text-secondary);">
        v0.1.0 · <span class="badge">live</span>
      </div>
    </aside>

    <main class="main">
      <header class="header">
        <div>
          <h1 class="title">Studio overview</h1>
          <p class="subtitle">Five sessions running. Two pending review.</p>
        </div>
        <div style="display: flex; gap: var(--space-3);">
          <button class="btn btn-ghost">Filter</button>
          <button class="btn">New session</button>
        </div>
      </header>

      <section class="grid">
        <div class="card">
          <span class="label">Active sessions</span>
          <span class="value">5</span>
          <span class="trend">+2 this hour</span>
        </div>
        <div class="card">
          <span class="label">Artifacts</span>
          <span class="value">128</span>
          <span class="trend">+11 today</span>
        </div>
        <div class="card">
          <span class="label">Tokens / hr</span>
          <span class="value">42.6k</span>
          <span class="trend">+8% vs avg</span>
        </div>
      </section>

      <div class="input-row">
        <input class="input" type="search" placeholder="Search sessions, artifacts, models..." />
        <button class="btn btn-ghost">⌘K</button>
      </div>

      <section class="panel">
        <h2>Recent activity</h2>
        <div class="row">
          <span class="who">Late-night dashboard mock</span>
          <span class="what">design_systems.update</span>
          <span class="when">2m ago</span>
        </div>
        <div class="row">
          <span class="who">Aurora landing — variant B</span>
          <span class="what">artifact.generate</span>
          <span class="when">14m ago</span>
        </div>
        <div class="row">
          <span class="who">Onboarding flow — pass 3</span>
          <span class="what">artifact.preview</span>
          <span class="when">31m ago</span>
        </div>
        <div class="row">
          <span class="who">Pricing comparison</span>
          <span class="what">artifact.export.pptx</span>
          <span class="when">1h ago</span>
        </div>
      </section>
    </main>
  </div>
</body>
</html>
`;

writeFileSync(join(__dirname, 'mockup.html'), mockHtml, 'utf8');

// ── Step 5: Print summary ────────────────────────────────────────────────────

console.log('\n=== Aurora design-system demo built ===\n');
console.log(`  DESIGN.md           → ${designMdPath}`);
console.log(
  `                        (parsed back: ${readFileSync(designMdPath, 'utf8').length} chars)`,
);
console.log(`  PROMPT_FRAGMENT.txt → ${join(__dirname, 'PROMPT_FRAGMENT.txt')}`);
console.log('                        (what the agent would see in its prompt)');
console.log(`  mockup.html         → ${join(__dirname, 'mockup.html')}`);
console.log('                        (open in a browser — Aurora applied)');
console.log('\nTokens injected into prompt:');
console.log(`  colors:     ${aurora.colors.length}`);
console.log(`  fonts:      ${aurora.fonts.length}`);
console.log(`  spacing:    ${aurora.spacing.length}`);
console.log(`  radius:     ${aurora.radius.length}`);
console.log(`  shadows:    ${aurora.shadows.length}`);
console.log(`  components: ${aurora.components?.length ?? 0}`);
console.log('');
