import { describe, expect, it } from 'vitest';
import { buildHtmlDocument } from './html';
import { requireRenderedHtml } from './index';

/**
 * Characterization + contract tests for the HTML exporter.
 *
 * Written as the first step of N0 (see the design QA plan, A2/A7). Before
 * this file, `html.ts` was the only exporter with zero coverage — which is
 * precisely how the "every export ships uncompiled JSX" bug shipped
 * unnoticed.
 *
 * Two groups below:
 *   1. `buildHtmlDocument` — the pure document-shell builder. Its behavior is
 *      correct *given real HTML*; these tests pin it so the N0 refactor
 *      cannot silently change it.
 *   2. The JSX regression net — the assertions that actually fail on the
 *      pre-N0 code path, proving the exporter must compile JSX before it
 *      ever reaches this builder.
 */

const JSX_ARTIFACT = `const TWEAK_DEFAULTS = /* EDITMODE-BEGIN */{ title: 'Hi' }/* EDITMODE-END */;
function App() {
  return <div className="p-4"><h1>{TWEAK_DEFAULTS.title}</h1></div>;
}
ReactDOM.createRoot(document.getElementById('root')).render(<App />);`;

describe('buildHtmlDocument — document shell', () => {
  it('wraps a bare fragment in a full document with a doctype', () => {
    const out = buildHtmlDocument('<p>hi</p>');
    expect(out).toMatch(/<!doctype html>/i);
    expect(out).toContain('<p>hi</p>');
    expect(out).toMatch(/<meta charset="utf-8"/i);
  });

  it('preserves an existing doctype rather than double-wrapping', () => {
    const doc = '<!doctype html>\n<html lang="en"><head></head><body><p>x</p></body></html>';
    const out = buildHtmlDocument(doc);
    expect(out.match(/<!doctype html>/gi)).toHaveLength(1);
    expect(out.match(/<html/gi)).toHaveLength(1);
  });

  it('adds a doctype to an <html> payload that lacks one', () => {
    const out = buildHtmlDocument('<html><body><p>x</p></body></html>');
    expect(out).toMatch(/<!doctype html>/i);
    expect(out.match(/<html/gi)).toHaveLength(1);
  });

  it('injects the Tailwind CDN by default', () => {
    const out = buildHtmlDocument('<p>hi</p>');
    expect(out).toContain('cdn.tailwindcss.com');
  });

  it('does not inject Tailwind twice when already present', () => {
    const withTw =
      '<html><head><script src="https://cdn.tailwindcss.com"></script></head><body/></html>';
    const out = buildHtmlDocument(withTw);
    expect(out.match(/cdn\.tailwindcss\.com/gi)).toHaveLength(1);
  });

  it('honours injectTailwind: false', () => {
    const out = buildHtmlDocument('<p>hi</p>', { injectTailwind: false });
    expect(out).not.toContain('cdn.tailwindcss.com');
  });

  it('injects the generator meta tag', () => {
    const out = buildHtmlDocument('<p>hi</p>');
    expect(out).toMatch(/<meta name="generator" content="atv-design"/i);
  });

  it('prepends the banner comment and honours an override', () => {
    expect(buildHtmlDocument('<p>hi</p>')).toMatch(/^<!-- Generated by atv-design/);
    expect(buildHtmlDocument('<p>hi</p>', { bannerComment: 'custom' })).toMatch(/^<!-- custom -->/);
  });

  it('is idempotent enough to survive a second pass without duplicating the shell', () => {
    const once = buildHtmlDocument('<p>hi</p>');
    const twice = buildHtmlDocument(once);
    expect(twice.match(/<!doctype html>/gi)).toHaveLength(1);
    expect(twice.match(/cdn\.tailwindcss\.com/gi)).toHaveLength(1);
  });

  it('stays stable across a third pass (banner comments do not accumulate shells)', () => {
    const thrice = buildHtmlDocument(buildHtmlDocument(buildHtmlDocument('<p>hi</p>')));
    expect(thrice.match(/<!doctype html>/gi)).toHaveLength(1);
    expect(thrice.match(/<html/gi)).toHaveLength(1);
  });

  it('sees past multiple stacked leading comments to find the doctype', () => {
    const doc = '<!-- one -->\n<!-- two -->\n<!doctype html>\n<html><body>x</body></html>';
    const out = buildHtmlDocument(doc);
    expect(out.match(/<!doctype html>/gi)).toHaveLength(1);
  });

  it('does not wrap a second shell around a custom-bannered document', () => {
    const once = buildHtmlDocument('<p>hi</p>', { bannerComment: 'custom banner' });
    const twice = buildHtmlDocument(once, { bannerComment: 'custom banner' });
    expect(twice.match(/<!doctype html>/gi)).toHaveLength(1);
  });

  it('tolerates an unterminated leading comment without hanging or throwing', () => {
    // `stripLeadingComments` breaks out when no `-->` is found; the payload is
    // then treated as a bare fragment and wrapped. The contract asserted here
    // is only that it terminates and emits a single shell.
    const out = buildHtmlDocument('<!-- never closed\n<p>hi</p>');
    expect(out.match(/<!doctype html>/gi)).toHaveLength(1);
  });

  it('handles an IE conditional comment ahead of the doctype', () => {
    const doc = '<!--[if IE]><![endif]-->\n<!doctype html>\n<html><body>x</body></html>';
    expect(buildHtmlDocument(doc).match(/<!doctype html>/gi)).toHaveLength(1);
  });

  it('does not mangle <script> and <pre> bodies while prettifying', () => {
    const out = buildHtmlDocument('<pre>a\n  b</pre>');
    expect(out).toContain('<pre>');
    expect(out).toContain('b');
  });
});

/**
 * The N0 regression net.
 *
 * `buildHtmlDocument` is a *string* transform: it cannot tell JSX from HTML.
 * Handed the agent's raw artifact it happily emits a doctype and a Tailwind
 * tag around literal JSX text — a file that passes a naive "has a doctype"
 * assertion and opens to a blank page.
 *
 * These tests pin that failure mode at the unit level so the compile step
 * added in N0 has something to turn green, and so a future refactor that
 * removes the compile step fails loudly here rather than in a user's export.
 */
describe('buildHtmlDocument — JSX must never reach it (N0 regression net)', () => {
  it('demonstrates the bug: raw JSX is wrapped, not compiled', () => {
    const out = buildHtmlDocument(JSX_ARTIFACT);

    // It looks like a valid document...
    expect(out).toMatch(/<!doctype html>/i);
    // ...but the body is literal, unexecutable JSX source.
    expect(out).toContain('function App()');
    expect(out).toContain('ReactDOM.createRoot');
    // And nothing that could ever execute it came along for the ride.
    expect(out).not.toContain('text/babel');
    expect(out.toLowerCase()).not.toContain('react.production');
  });

  it('a doctype assertion alone would certify the broken output', () => {
    // Documents why the originally-specified E2E assertion was insufficient:
    // the doctype is prepended unconditionally, so it proves nothing about
    // whether the artifact was compiled.
    expect(buildHtmlDocument(JSX_ARTIFACT)).toMatch(/^<!-- .*-->\n<!doctype html>/is);
  });
});

describe('requireRenderedHtml — the dispatch guard', () => {
  it('passes rendered HTML through', () => {
    expect(requireRenderedHtml({ kind: 'html', source: '<p>hi</p>' })).toBe('<p>hi</p>');
  });

  it('rejects a jsx-tagged artifact with EXPORTER_COMPILE_FAILED', () => {
    expect(() => requireRenderedHtml({ kind: 'jsx', source: JSX_ARTIFACT })).toThrowError(
      expect.objectContaining({ code: 'EXPORTER_COMPILE_FAILED' }),
    );
  });
});
