import type { ExportResult } from './index';

const TAILWIND_CDN = 'https://cdn.tailwindcss.com';
const TAILWIND_TAG = `<script src="${TAILWIND_CDN}"></script>`;

export interface ExportHtmlOptions {
  /** Inject the Tailwind CDN script if missing. Defaults to true. */
  injectTailwind?: boolean;
  /** Prettify with two-space indentation. Defaults to true. */
  prettify?: boolean;
  /** Comment banner injected at the top of the file. */
  bannerComment?: string;
}

/**
 * Export an HTML artifact to disk as a single self-contained file.
 *
 * `renderedHtml` is **compiled** HTML — the caller is responsible for running
 * the agent's JSX through `buildSrcdoc` first (see `ArtifactSource` in
 * `./index`). This function cannot tell JSX from HTML and will happily wrap
 * raw source in a doctype if handed it.
 *
 * Tier 1 inlines what we can do without parsing the DOM: the Tailwind CDN
 * tag, a doctype, a viewport meta, and a small comment banner. Anything that
 * needs a real HTML parser (font subsetting, SVG inlining, JS bundling) waits
 * for Tier 2 — and is loud about it: never silently skip work the caller
 * believed we did.
 */
export async function exportHtml(
  renderedHtml: string,
  destinationPath: string,
  opts: ExportHtmlOptions = {},
): Promise<ExportResult> {
  const fs = await import('node:fs/promises');
  const final = buildHtmlDocument(renderedHtml, opts);
  await fs.writeFile(destinationPath, final, 'utf8');
  const stat = await fs.stat(destinationPath);
  return { bytes: stat.size, path: destinationPath };
}

export function buildHtmlDocument(renderedHtml: string, opts: ExportHtmlOptions = {}): string {
  const injectTailwind = opts.injectTailwind ?? true;
  const prettify = opts.prettify ?? true;
  const banner =
    opts.bannerComment ?? 'Generated by atv-design — https://github.com/All-The-Vibes/ATV-Design';

  let out = ensureDocumentShell(renderedHtml);
  if (injectTailwind && !hasTailwindScript(out)) {
    out = injectIntoHead(out, TAILWIND_TAG);
  }
  out = injectIntoHead(out, `<meta name="generator" content="atv-design" />`);
  out = `<!-- ${banner} -->\n${out}`;
  if (prettify) out = prettifyHtml(out);
  return out;
}

function ensureDocumentShell(html: string): string {
  const trimmed = html.trim();
  // Sniff past any leading comments before deciding whether this is already a
  // document. `buildHtmlDocument` prepends its own banner comment, so without
  // this the builder fails to recognise its own output and wraps a second
  // doctype around it (invalid HTML on any re-export / round-trip).
  const sniff = stripLeadingComments(trimmed);
  if (/^<!doctype/i.test(sniff)) return trimmed;
  if (/<html[\s>]/i.test(trimmed)) return `<!doctype html>\n${trimmed}`;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>atv-design export</title>
</head>
<body>
${trimmed}
</body>
</html>`;
}

function hasTailwindScript(html: string): boolean {
  return /cdn\.tailwindcss\.com/i.test(html);
}

/** Drop leading `<!-- ... -->` comments (and surrounding whitespace). */
function stripLeadingComments(html: string): string {
  let out = html.trimStart();
  while (out.startsWith('<!--')) {
    const end = out.indexOf('-->');
    if (end === -1) break;
    out = out.slice(end + 3).trimStart();
  }
  return out;
}

function injectIntoHead(html: string, tag: string): string {
  if (/<head[\s>]/i.test(html)) {
    return html.replace(/<head([^>]*)>/i, (m) => `${m}\n  ${tag}`);
  }
  if (/<html[^>]*>/i.test(html)) {
    return html.replace(/<html([^>]*)>/i, (m) => `${m}\n<head>\n  ${tag}\n</head>`);
  }
  return `${tag}\n${html}`;
}

/**
 * Indentation-only prettifier. Splits inline tags onto fresh lines and
 * reflows indentation. We deliberately avoid pulling in `prettier` /
 * `js-beautify` (would blow the dep budget) — Tier 2 can swap this out.
 */
function prettifyHtml(html: string): string {
  const tokens = html.replace(/>\s+</g, '><').replace(/></g, '>\n<').split('\n');

  const voidElements = new Set([
    'area',
    'base',
    'br',
    'col',
    'embed',
    'hr',
    'img',
    'input',
    'link',
    'meta',
    'param',
    'source',
    'track',
    'wbr',
  ]);
  const inline = new Set(['script', 'style', 'pre', 'textarea']);

  let depth = 0;
  let inInline: string | null = null;
  const lines: string[] = [];

  for (const raw of tokens) {
    const line = raw.trim();
    if (!line) continue;

    if (inInline) {
      lines.push(line);
      if (new RegExp(`</${inInline}\\s*>`, 'i').test(line)) {
        inInline = null;
        depth = Math.max(0, depth - 1);
      }
      continue;
    }

    const closing = /^<\//.test(line);
    const selfClosing = /\/>\s*$/.test(line) || isVoidTag(line, voidElements);
    const isComment = /^<!--/.test(line);
    const isDoctype = /^<!doctype/i.test(line);

    if (closing) depth = Math.max(0, depth - 1);

    lines.push(`${'  '.repeat(depth)}${line}`);

    const tagName = openTagName(line);
    if (tagName && inline.has(tagName) && !selfClosing) {
      const sameLine = new RegExp(`</${tagName}\\s*>`, 'i').test(line);
      if (!sameLine) {
        inInline = tagName;
        depth += 1;
      }
      continue;
    }

    if (!closing && !selfClosing && !isComment && !isDoctype && tagName) {
      depth += 1;
    }
  }

  return `${lines.join('\n')}\n`;
}

function openTagName(line: string): string | null {
  const m = /^<([a-zA-Z][a-zA-Z0-9-]*)/.exec(line);
  return m ? (m[1] as string).toLowerCase() : null;
}

function isVoidTag(line: string, voids: Set<string>): boolean {
  const name = openTagName(line);
  return name !== null && voids.has(name);
}
